# Generated by Django 3.1 on 2020-08-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of the fixed expense:')),
                ('price', models.FloatField(default=0.0, verbose_name='Value of the expense:')),
                ('month', models.CharField(choices=[('JAN', 'JANUARY'), ('FEB', 'FEBRUARY'), ('MAR', 'MARCH'), ('APR', 'APRIL'), ('MAY', 'MAY'), ('JUN', 'JUNE'), ('JUL', 'JULY'), ('AUG', 'AUGUST'), ('SEP', 'SEPTEMBER'), ('OCT', 'OCTOBER'), ('NOV', 'NOVEMBER'), ('DEC', 'DECEMBER')], default='AUG', max_length=3, verbose_name='Month of the expense:')),
            ],
        ),
        migrations.AlterField(
            model_name='grocerylist',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name of the product:'),
        ),
        migrations.AlterField(
            model_name='grocerylist',
            name='quantity',
            field=models.FloatField(default=1.0, verbose_name='Quantity:'),
        ),
        migrations.AlterField(
            model_name='grocerylist',
            name='unit_price',
            field=models.FloatField(default=0.0, verbose_name='Unit Price:'),
        ),
    ]
