# Generated by Django 3.1 on 2020-08-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20200819_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetcontrol',
            old_name='month',
            new_name='fixed_expense_month',
        ),
        migrations.RenameField(
            model_name='budgetcontrol',
            old_name='name',
            new_name='fixed_expense_name',
        ),
        migrations.RenameField(
            model_name='budgetcontrol',
            old_name='price',
            new_name='fixed_expense_price',
        ),
        migrations.AddField(
            model_name='budgetcontrol',
            name='fixed_earnings_month',
            field=models.CharField(choices=[('JAN', 'JANUARY'), ('FEB', 'FEBRUARY'), ('MAR', 'MARCH'), ('APR', 'APRIL'), ('MAY', 'MAY'), ('JUN', 'JUNE'), ('JUL', 'JULY'), ('AUG', 'AUGUST'), ('SEP', 'SEPTEMBER'), ('OCT', 'OCTOBER'), ('NOV', 'NOVEMBER'), ('DEC', 'DECEMBER')], default='AUG', max_length=3, verbose_name='Month of the earn:'),
        ),
        migrations.AddField(
            model_name='budgetcontrol',
            name='fixed_earnings_name',
            field=models.CharField(default='teste', max_length=255, verbose_name='Name of the fixed earn:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budgetcontrol',
            name='fixed_earnings_price',
            field=models.FloatField(default=0.0, verbose_name='Value of the earn:'),
        ),
        migrations.AddField(
            model_name='budgetcontrol',
            name='investment_month',
            field=models.CharField(choices=[('JAN', 'JANUARY'), ('FEB', 'FEBRUARY'), ('MAR', 'MARCH'), ('APR', 'APRIL'), ('MAY', 'MAY'), ('JUN', 'JUNE'), ('JUL', 'JULY'), ('AUG', 'AUGUST'), ('SEP', 'SEPTEMBER'), ('OCT', 'OCTOBER'), ('NOV', 'NOVEMBER'), ('DEC', 'DECEMBER')], default='AUG', max_length=3, verbose_name='Month of the investment:'),
        ),
        migrations.AddField(
            model_name='budgetcontrol',
            name='investment_name',
            field=models.CharField(default='teste', max_length=255, verbose_name='Name of the investment:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budgetcontrol',
            name='investment_price',
            field=models.FloatField(default=0.0, verbose_name='Value of the investment:'),
        ),
        migrations.AddField(
            model_name='budgetcontrol',
            name='variable_costs_month',
            field=models.CharField(choices=[('JAN', 'JANUARY'), ('FEB', 'FEBRUARY'), ('MAR', 'MARCH'), ('APR', 'APRIL'), ('MAY', 'MAY'), ('JUN', 'JUNE'), ('JUL', 'JULY'), ('AUG', 'AUGUST'), ('SEP', 'SEPTEMBER'), ('OCT', 'OCTOBER'), ('NOV', 'NOVEMBER'), ('DEC', 'DECEMBER')], default='AUG', max_length=3, verbose_name='Month of the variable cost:'),
        ),
        migrations.AddField(
            model_name='budgetcontrol',
            name='variable_costs_name',
            field=models.CharField(default='teste', max_length=255, verbose_name='Name of the variable cost:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budgetcontrol',
            name='variable_costs_price',
            field=models.FloatField(default=0.0, verbose_name='Value of the variable cost:'),
        ),
    ]
