# Generated by Django 3.1 on 2020-08-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20200819_1432'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroceryList',
        ),
        migrations.RemoveField(
            model_name='budgetcontrol',
            name='fixed_earnings_month',
        ),
        migrations.RemoveField(
            model_name='budgetcontrol',
            name='fixed_earnings_name',
        ),
        migrations.RemoveField(
            model_name='budgetcontrol',
            name='fixed_earnings_price',
        ),
        migrations.RemoveField(
            model_name='budgetcontrol',
            name='fixed_expense_month',
        ),
        migrations.RemoveField(
            model_name='budgetcontrol',
            name='fixed_expense_name',
        ),
        migrations.RemoveField(
            model_name='budgetcontrol',
            name='fixed_expense_price',
        ),
        migrations.RemoveField(
            model_name='budgetcontrol',
            name='investment_month',
        ),
        migrations.RemoveField(
            model_name='budgetcontrol',
            name='investment_name',
        ),
        migrations.RemoveField(
            model_name='budgetcontrol',
            name='investment_price',
        ),
        migrations.RemoveField(
            model_name='budgetcontrol',
            name='variable_costs_month',
        ),
        migrations.RemoveField(
            model_name='budgetcontrol',
            name='variable_costs_name',
        ),
        migrations.RemoveField(
            model_name='budgetcontrol',
            name='variable_costs_price',
        ),
        migrations.AddField(
            model_name='budgetcontrol',
            name='category',
            field=models.CharField(choices=[('Profit', 'PROFIT'), ('Spend', 'SPEND'), ('Investment', 'INVESTMENT'), ('Good', 'GOOD')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='budgetcontrol',
            name='month',
            field=models.CharField(choices=[('JAN', 'JANUARY'), ('FEB', 'FEBRUARY'), ('MAR', 'MARCH'), ('APR', 'APRIL'), ('MAY', 'MAY'), ('JUN', 'JUNE'), ('JUL', 'JULY'), ('AUG', 'AUGUST'), ('SEP', 'SEPTEMBER'), ('OCT', 'OCTOBER'), ('NOV', 'NOVEMBER'), ('DEC', 'DECEMBER')], default='AUG', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='budgetcontrol',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='budgetcontrol',
            name='value',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
