# Generated by Django 3.1 on 2020-08-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20200820_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetcontrol',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
