# Generated by Django 3.1 on 2020-08-25 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_budgetcontrol_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetcontrol',
            name='user',
        ),
    ]
