# Generated by Django 3.1 on 2020-09-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_auto_20200825_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetcontrol',
            name='fixed',
            field=models.CharField(choices=[('VARIÁVEL', 'VARIÁVEL'), ('FIXO', 'FIXO')], default='VARIÁVEL', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='budgetcontrol',
            name='category',
            field=models.CharField(choices=[('RECEITA', 'RECEITA'), ('GASTO', 'GASTO'), ('INVESTIMENTO', 'INVESTIMENTO'), ('BEM', 'BEM')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='budgetcontrol',
            name='month',
            field=models.CharField(choices=[('JAN', 'JANEIRO'), ('FEV', 'FEVEREIRO'), ('MAR', 'MARÇO'), ('ABR', 'ABRIL'), ('MAI', 'MAIO'), ('JUN', 'JUNHO'), ('JUL', 'JULHO'), ('AGO', 'AGOSTO'), ('SET', 'SETEMBRO'), ('OUT', 'OUTUBRO'), ('NOV', 'NOVEMBRO'), ('DEZ', 'DEZEMBRO')], default='SET', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='budgetcontrol',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
