# Generated by Django 3.1 on 2020-09-17 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first_app', '0010_auto_20200916_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetcontrol',
            name='fixed',
        ),
        migrations.CreateModel(
            name='FixedValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(choices=[('RECEITA', 'RECEITA'), ('GASTO', 'GASTO'), ('INVESTIMENTO', 'INVESTIMENTO'), ('BEM', 'BEM')], max_length=12, null=True)),
                ('value', models.FloatField(null=True)),
                ('month', models.CharField(choices=[('JAN', 'JANEIRO'), ('FEV', 'FEVEREIRO'), ('MAR', 'MARÇO'), ('ABR', 'ABRIL'), ('MAI', 'MAIO'), ('JUN', 'JUNHO'), ('JUL', 'JULHO'), ('AGO', 'AGOSTO'), ('SET', 'SETEMBRO'), ('OUT', 'OUTUBRO'), ('NOV', 'NOVEMBRO'), ('DEZ', 'DEZEMBRO')], default='SET', max_length=3, null=True)),
                ('fixed', models.CharField(choices=[('VARIÁVEL', 'VARIÁVEL'), ('FIXO', 'FIXO')], default='VARIÁVEL', max_length=12, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
