# Generated by Django 3.1 on 2020-09-17 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0011_auto_20200917_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixedvalues',
            name='month',
        ),
    ]
