# Generated by Django 3.1 on 2020-09-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0013_auto_20200925_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetcontrol',
            name='category',
            field=models.CharField(choices=[('RECEITA', 'RECEITA'), ('GASTO', 'GASTO'), ('INVESTIMENTO', 'INVESTIMENTO')], max_length=12, null=True),
        ),
    ]
