# Generated by Django 3.1 on 2020-09-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0014_auto_20200926_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedvalues',
            name='category',
            field=models.CharField(choices=[('RECEITA', 'RECEITA'), ('GASTO', 'GASTO'), ('INVESTIMENTO', 'INVESTIMENTO')], max_length=12, null=True),
        ),
    ]
