# Generated by Django 3.1 on 2020-10-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0015_auto_20200926_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetcontrol',
            name='month',
            field=models.CharField(choices=[('JANEIRO', 'JANEIRO'), ('FEVEREIRO', 'FEVEREIRO'), ('MARÇO', 'MARÇO'), ('ABRIL', 'ABRIL'), ('MAIO', 'MAIO'), ('JUNHO', 'JUNHO'), ('JULHO', 'JULHO'), ('AGOSTO', 'AGOSTO'), ('SETEMBRO', 'SETEMBRO'), ('OUTUBRO', 'OUTUBRO'), ('NOVEMBRO', 'NOVEMBRO'), ('DEZEMBRO', 'DEZEMBRO')], default='OUTUBRO', max_length=10, null=True),
        ),
    ]
